apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: solar-system
  labels:
    app: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: solar-system-sa
      containers:
        - name: frontend
          image: mraidiachref/solar-system:998c1e162437ba5841ad99cad429c9921840cb1e
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: solar-system-secrets
