apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"  
      path: "kv"                               
      version: "v2"
      auth:
        kubernetes:
            mountPath: "kubernetes"            
            role: "solar-system-role"
            serviceAccountRef:
              name: solar-system-sa
              namespace: solar-system
