apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: solar-system-secrets
  namespace: solar-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: solar-system-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGO_URI
      remoteRef:
        key: solar-system-app/prod/db   
        property: MONGO_URI
