apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: solar-system
  labels:
    app: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
